# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('project_status', models.CharField(choices=[(b'0', b'Started'), (b'1', b'In Progress'), (b'2', b'Closed')], max_length=20)),
                ('topic', models.CharField(max_length=100)),
                ('deployed', models.BooleanField(default=False)),
                ('project_effort', models.IntegerField()),
                ('public_domain', models.URLField(null=True)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('ready', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[(b'0', b'High'), (b'1', b'Normal'), (b'2', b'Low')], max_length=10)),
                ('ticket_status', models.CharField(choices=[(b'0', b'Tested'), (b'1', b'Completed'), (b'2', b'In Progress'), (b'3', b'Created'), (b'4', b'Cancelled')], default='Created', max_length=10)),
                ('difficulty', models.CharField(choices=[(b'0', b'very hard'), (b'1', b'hard'), (b'2', b'standard'), (b'3', b'simple'), (b'4', b'very simple')], max_length=10)),
                ('ticket_effort', models.DecimalField(decimal_places=1, max_digits=3)),
                ('opened_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField()),
                ('delivery', models.DateField()),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
