# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[(b'Started', b'Started'), (b'In Progress', b'In Progress'), (b'Closed', b'Closed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='difficulty',
            field=models.CharField(choices=[(b'very hard', b'very hard'), (b'hard', b'hard'), (b'standard', b'standard'), (b'simple', b'simple'), (b'very simple', b'very simple')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[(b'High', b'High'), (b'Normal', b'Normal'), (b'Low', b'Low')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[(b'Tested', b'Tested'), (b'Completed', b'Completed'), (b'In Progres', b'In Progress'), (b'Created', b'Created'), (b'Cancelled', b'Cancelled')], default='Created', max_length=10),
        ),
    ]
